using BrutalAPI;
using BrutalAPI.Items;
using System;
using System.Collections.Generic;
using System.Runtime.Versioning;
using System.Text;
using UnityEngine;
using UnityEngine.SocialPlatforms;

namespace AprilsDayAtFools
{
    public static class MarchItems
    {
        public static void Add()
        {
            Basic_Item merced = new Basic_Item("Aprils_ThePeopleOfPaper_TW");
            merced.Name = "Salvador Plascencia's \"The People Of Paper\"";
            merced.Flavour = "\"She was made after the time of ribs and mud.\"";
            merced.Description = "This party member obliterates when they die.";
            merced.Icon = ResourceLoader.LoadSprite("item_thepeopleofpaper.png");
            merced.EquippedModifiers = [];
            merced.TriggerOn = TriggerCalls.Count;
            merced.DoesPopUpInfo = false;
            merced.Conditions = [];
            merced.DoesActionOnTriggerAttached = false;
            merced.ConsumeOnTrigger = TriggerCalls.Count;
            merced.ConsumeOnUse = false;
            merced.ConsumeConditions = [];
            merced.ShopPrice = 0;
            merced.IsShopItem = false;
            merced.StartsLocked = true;
            merced.OnUnlockUsesTHE = false;
            merced.UsesSpecialUnlockText = false;
            merced.SpecialUnlockID = UILocID.None;
            merced.item.AddItem("locked_thepeopleofpaper.png", "Aprils_Merced_March_ACH");

            CopyCasterAndSpawnCharacterAnywhereEffect copyself = ScriptableObject.CreateInstance<CopyCasterAndSpawnCharacterAnywhereEffect>();
            copyself._rankIsAdditive = true;
            copyself._permanentSpawn = false;
            copyself._canGetDeadCharacter = true;
            copyself._extraModifiers = [];
            copyself._maximizeHealth = true;

            PerformEffect_Item cora = new PerformEffect_Item("Aprils_WitchsHeart_TW", [
                Effects.GenerateEffect(ScriptableObject.CreateInstance<DirectDeathEffect>(), 0, Slots.Self),
                Effects.GenerateEffect(copyself, 5, Slots.Self)
                ]);
            cora.Name = "Witch's Heart";
            cora.Flavour = "\"Swan Song\"";
            cora.Description = "At the start of combat, instantly kill this party member and spawn as many same level nonpermenant clones of them as possible.\nDoes not work on Nowak.";
            cora.Icon = ResourceLoader.LoadSprite("item_witchsheart.png");
            cora.EquippedModifiers = [];
            cora.TriggerOn = TriggerCalls.OnCombatStart;
            cora.DoesPopUpInfo = true;
            cora.Conditions = [ScriptableObject.CreateInstance<IsMainCharacterEffectorCondition>()];
            cora.DoesActionOnTriggerAttached = false;
            cora.ConsumeOnTrigger = TriggerCalls.Count;
            cora.ConsumeOnUse = false;
            cora.ConsumeConditions = [];
            cora.ShopPrice = 5;
            cora.IsShopItem = false;
            cora.StartsLocked = true;
            cora.OnUnlockUsesTHE = true;
            cora.UsesSpecialUnlockText = false;
            cora.SpecialUnlockID = UILocID.None;
            cora.item._ItemTypeIDs = ["Heart", "Magic"];
            cora.item.AddItem("locked_witchsheart.png", "Aprils_Cora_March_ACH");

            ExtraPassiveAbility_Wearable_SMS frail = ScriptableObject.CreateInstance<ExtraPassiveAbility_Wearable_SMS>();
            frail._extraPassiveAbility = Passives.Enfeebled;

            PerformEffect_Item xet = new PerformEffect_Item("Aprils_MachineEgg_TW", []);
            xet.Name = "Machine Egg";
            xet.Flavour = "\"Yours, Truly\"";
            xet.Description = "This party member is immune to Shield and has \"Enfeebled\" as a passive.\nIncrease damage dealt by the amount of Shield on this party member's position.";
            xet.Icon = ResourceLoader.LoadSprite("item_machineegg.png");
            xet.EquippedModifiers = [frail];
            xet.TriggerOn = TriggerCalls.OnWillApplyDamage;
            xet.DoesPopUpInfo = false;
            xet.Conditions = [ScriptableObject.CreateInstance<IncreaseDamageByShieldCondition>()];
            xet.DoesActionOnTriggerAttached = false;
            xet.ConsumeOnTrigger = TriggerCalls.Count;
            xet.ConsumeOnUse = false;
            xet.ConsumeConditions = [];
            xet.ShopPrice = 10;
            xet.IsShopItem = false;
            xet.StartsLocked = true;
            xet.OnUnlockUsesTHE = true;
            xet.UsesSpecialUnlockText = false;
            xet.SpecialUnlockID = UILocID.None;
            xet.item._ItemTypeIDs = ["IgnoreShield", "Heart"];
            xet.item.AddItem("locked_machineegg.png", "Aprils_Xet_March_ACH");

            TrackIntegerReferenceCondition heal8 = ScriptableObject.CreateInstance<TrackIntegerReferenceCondition>();
            heal8.StoredValue = "Aprils_Overdose_SW";
            heal8.Above = 8;

            MultiPerformEffectItem saline = new MultiPerformEffectItem("Aprils_Overdose_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<HealEffect>(), 2, Slots.Self)]);
            saline.Name = "Overdose";
            saline.Flavour = "\"Escape is not an escape.\"";
            saline.Description = "Heal this party member 2 health at the start of each turn.\nIf the total amount of healing this party member received exceeds 8, Curse them.";
            saline.Icon = ResourceLoader.LoadSprite("item_overdose.png");
            saline.EquippedModifiers = [];
            saline.TriggerOn = TriggerCalls.OnTurnStart;
            saline.DoesPopUpInfo = true;
            saline.Conditions = [];
            saline.DoesActionOnTriggerAttached = false;
            saline.ConsumeOnTrigger = TriggerCalls.Count;
            saline.ConsumeOnUse = false;
            saline.ConsumeConditions = [];
            saline.ShopPrice = 5;
            saline.IsShopItem = true;
            saline.StartsLocked = true;
            saline.OnUnlockUsesTHE = true;
            saline.UsesSpecialUnlockText = false;
            saline.SpecialUnlockID = UILocID.None;
            saline.item._ItemTypeIDs = [];
            EffectTrigger saline_second = new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyCursedEffect>(), 1, Slots.Self)], [TriggerCalls.OnHealed], [heal8]);
            saline.AddEffectTrigger(saline_second);
            saline.item.AddItem("locked_overdose.png", "Aprils_Saline_March_ACH");

            PerformEffect_Item didion = new PerformEffect_Item("Aprils_LoversPact_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyFocusedEffect>(), 1, Targeting.Slot_AllyLeft)]);
            didion.Name = "Lover's Pact";
            didion.Flavour = "\"For You.\"";
            didion.Description = "Whenever the Left ally takes any damage, Focus them.";
            didion.Icon = ResourceLoader.LoadSprite("item_loverspact.png");
            didion.EquippedModifiers = [];
            didion.TriggerOn = SidesDamagedHandler.LeftDamaged;
            didion.DoesPopUpInfo = true;
            didion.Conditions = [];
            didion.DoesActionOnTriggerAttached = false;
            didion.ConsumeOnTrigger = TriggerCalls.Count;
            didion.ConsumeOnUse = false;
            didion.ConsumeConditions = [];
            didion.ShopPrice = 7;
            didion.IsShopItem = true;
            didion.StartsLocked = true;
            didion.OnUnlockUsesTHE = true;
            didion.UsesSpecialUnlockText = false;
            didion.SpecialUnlockID = UILocID.None;
            didion.item._ItemTypeIDs = ["Heart"];
            didion.item.AddItem("locked_loverspact.png", "Aprils_Didion_March_ACH");

            StatusEffect_Apply_Effect spotlight = ScriptableObject.CreateInstance<StatusEffect_Apply_Effect>();
            spotlight._Status = StatusField.Spotlight;

            PerformEffect_Item rose = new PerformEffect_Item("Aprils_SundayGallows_SW", [Effects.GenerateEffect(spotlight, 1, Slots.Front)]);
            rose.Name = "Sunday Gallows";
            rose.Flavour = "\"Did you hear they finally put that monster down?\"";
            rose.Description = "On taking any damage, apply Spotlight to the Opposing enemy.";
            rose.Icon = ResourceLoader.LoadSprite("item_sundaygallows.png");
            rose.EquippedModifiers = [];
            rose.TriggerOn = TriggerCalls.OnDamaged;
            rose.DoesPopUpInfo = true;
            rose.Conditions = [];
            rose.DoesActionOnTriggerAttached = false;
            rose.ConsumeOnTrigger = TriggerCalls.Count;
            rose.ConsumeOnUse = false;
            rose.ConsumeConditions = [];
            rose.ShopPrice = 7;
            rose.IsShopItem = true;
            rose.StartsLocked = true;
            rose.OnUnlockUsesTHE = true;
            rose.UsesSpecialUnlockText = false;
            rose.SpecialUnlockID = UILocID.None;
            rose.item._ItemTypeIDs = ["Fabric"];
            rose.item.AddItem("locked_sundagallows.png", "Aprils_Rose_March_ACH");

            PercentageEffectorCondition quarter = ScriptableObject.CreateInstance<PercentageEffectorCondition>();
            quarter.triggerPercentage = 25;
            PercentageEffectorCondition forty = ScriptableObject.CreateInstance<PercentageEffectorCondition>();
            forty.triggerPercentage = 40;

            MultiPerformEffectItem prayer = new MultiPerformEffectItem("Aprils_TheHumanAlgorithm_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<SwapToSidesEffect>(), 1, Slots.Self)]);
            prayer.Name = "The Human Algorithm";
            prayer.Flavour = "\"Tells you what to do for you!\"";
            prayer.Description = "On manually moving, 25% chance to move Left or Right.\nOn manually using an ability, 40% chance to use a random ability.";
            prayer.Icon = ResourceLoader.LoadSprite("item_thehumanalgorithm.png");
            prayer.EquippedModifiers = [];
            prayer.TriggerOn = TriggerCalls.OnSwapTo;
            prayer.DoesPopUpInfo = true;
            prayer.Conditions = [quarter];
            prayer.DoesActionOnTriggerAttached = false;
            prayer.ConsumeOnTrigger = TriggerCalls.Count;
            prayer.ConsumeOnUse = false;
            prayer.ConsumeConditions = [];
            prayer.ShopPrice = 6;
            prayer.IsShopItem = false;
            prayer.StartsLocked = true;
            prayer.OnUnlockUsesTHE = false;
            prayer.UsesSpecialUnlockText = false;
            prayer.SpecialUnlockID = UILocID.None;
            prayer.item._ItemTypeIDs = ["Heart"];
            EffectTrigger prayer_second = new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<PerformRandomAbilityEffect>(), 1, Slots.Self)], [TriggerCalls.OnAbilityUsed], [forty]);
            prayer.AddEffectTrigger(prayer_second);
            prayer.item.AddItem("locked_thehumanalgorithm.png", "Aprils_Prayer_March_ACH");

            MaxHealthChange_Wearable_SMS less = ScriptableObject.CreateInstance<MaxHealthChange_Wearable_SMS>();
            less.isChangePercentage = true;
            less.maxHealthChange = -30;

            PerformEffect_Item kafka = new PerformEffect_Item("Aprils_ShrunkenDoor_TW", []);
            kafka.Name = "Shrunken Door";
            kafka.Flavour = "\"Adventures in Wonderland\"";
            kafka.Description = "Double all healing received.\nThis party member has 30% less maximum health.";
            kafka.Icon = ResourceLoader.LoadSprite("item_shrunkendoor.png");
            kafka.EquippedModifiers = [less];
            kafka.TriggerOn = TriggerCalls.OnBeingHealed;
            kafka.DoesPopUpInfo = true;
            kafka.Conditions = [ScriptableObject.CreateInstance<DoubleHealingReceivedCondition>()];
            kafka.DoesActionOnTriggerAttached = false;
            kafka.ConsumeOnTrigger = TriggerCalls.Count;
            kafka.ConsumeOnUse = false;
            kafka.ConsumeConditions = [];
            kafka.ShopPrice = 5;
            kafka.IsShopItem = false;
            kafka.StartsLocked = true;
            kafka.OnUnlockUsesTHE = true;
            kafka.UsesSpecialUnlockText = false;
            kafka.SpecialUnlockID = UILocID.None;
            kafka.item._ItemTypeIDs = ["Magic"];
            kafka.item.AddItem("locked_shrunkendoor.png", "Aprils_Kafka_March_ACH");

            RemoveFieldEffectEffect remShield = ScriptableObject.CreateInstance<RemoveFieldEffectEffect>();
            remShield._field = StatusField.Shield;

            PerformEffect_Item bodybag = new PerformEffect_Item("Aprils_Headstone_TW", [Effects.GenerateEffect(remShield, 1, Slots.Self)]);
            bodybag.Name = "Headstone";
            bodybag.Flavour = "\"Death 2.\"";
            bodybag.Description = "On death, once per combat, prevent it and heal for the amount of Shield on this party member, then remove all Shield from them.\nDoes not work if this party member is not in Shield or if this party member cannot be healed.";
            bodybag.Icon = ResourceLoader.LoadSprite("item_headstone.png");
            bodybag.EquippedModifiers = [];
            bodybag.TriggerOn = TriggerCalls.CanDie;
            bodybag.DoesPopUpInfo = false;
            bodybag.Conditions = [ScriptableObject.CreateInstance<HeadstoneCondition>()];
            bodybag.DoesActionOnTriggerAttached = false;
            bodybag.ConsumeOnTrigger = TriggerCalls.Count;
            bodybag.ConsumeOnUse = false;
            bodybag.ConsumeConditions = [];
            bodybag.ShopPrice = 8;
            bodybag.IsShopItem = false;
            bodybag.StartsLocked = true;
            bodybag.OnUnlockUsesTHE = true;
            bodybag.UsesSpecialUnlockText = false;
            bodybag.SpecialUnlockID = UILocID.None;
            bodybag.item.AddItem("locked_headstone.png", "Aprils_Bodybag_March_ACH");

            MultiPerformEffectItem hangman = new MultiPerformEffectItem("Aprils_Euthanasia_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<DirectDeathEffect>(), 1, Slots.Self)]);
            hangman.Name = "Euthanasia";
            hangman.Flavour = "\"Have you tried turning it off and on again?\"";
            hangman.Description = "On taking any damage, if this party member is below half health instantly die. \nIncrease damage dealt by the Left and Right allies by this party member's missing health.\nThis item is destroyed upon death.";
            hangman.Icon = ResourceLoader.LoadSprite("item_euthanasia.png");
            hangman.EquippedModifiers = [];
            hangman.TriggerOn = TriggerCalls.OnDamaged;
            hangman.DoesPopUpInfo = true;
            hangman.Conditions = [ScriptableObject.CreateInstance<UnderHalfHealthCondition>()];
            hangman.DoesActionOnTriggerAttached = false;
            hangman.ConsumeOnTrigger = TriggerCalls.OnDeath;
            hangman.ConsumeOnUse = false;
            hangman.ConsumeConditions = [];
            hangman.ShopPrice = 6;
            hangman.IsShopItem = true;
            hangman.StartsLocked = true;
            hangman.OnUnlockUsesTHE = false;
            hangman.UsesSpecialUnlockText = false;
            hangman.SpecialUnlockID = UILocID.None;
            EffectTrigger hangman_second = new EffectTrigger([], [SidesWillApplyDamageHandler.SidesApply], [ScriptableObject.CreateInstance<DamageByMissingHealthCondition>()], false);
            hangman.AddEffectTrigger(hangman_second);
            hangman.item.AddItem("locked_euthanasia.png", "Aprils_Hangman_March_ACH");

            IncreaseDamageBySlotsCondition leftright = ScriptableObject.CreateInstance<IncreaseDamageBySlotsCondition>();
            leftright.ValidSlots = [1, 3];

            PerformEffect_Item saturn = new PerformEffect_Item("Aprils_BoundaryLines_SW", []);
            saturn.Name = "Boundary Lines";
            saturn.Flavour = "\"If you walk over there, you'll pass through the barrier between life and death...\"";
            saturn.Description = "Deal 25% more daamge while in the 2nd or 4th position.\nDeal 25% less damage otherwise.";
            saturn.Icon = ResourceLoader.LoadSprite("item_boundarylines.png");
            saturn.EquippedModifiers = [];
            saturn.TriggerOn = TriggerCalls.OnWillApplyDamage;
            saturn.DoesPopUpInfo = false;
            saturn.Conditions = [leftright];
            saturn.DoesActionOnTriggerAttached = false;
            saturn.ConsumeOnTrigger = TriggerCalls.Count;
            saturn.ConsumeOnUse = false;
            saturn.ConsumeConditions = [];
            saturn.ShopPrice = 4;
            saturn.IsShopItem = true;
            saturn.StartsLocked = true;
            saturn.OnUnlockUsesTHE = true;
            saturn.UsesSpecialUnlockText = false;
            saturn.SpecialUnlockID = UILocID.None;
            saturn.item._ItemTypeIDs = [];
            saturn.item.AddItem("locked_boundarylines.png", "Aprils_Saturn_March_ACH");

            RandomStatusEffect positives = ScriptableObject.CreateInstance<RandomStatusEffect>();
            positives.CanApply = ["Focused_ID", "WildCard_ID", "Anesthetics_ID", "Power_ID", "Determined_ID", "Photo_ID", "Dodge_ID", "Haste_ID"];

            PerformEffect_Item hare = new PerformEffect_Item("Aprils_Clay_SW", [
                Effects.GenerateEffect(positives, 1, Slots.Self),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomStatusEffect>(), 1, Slots.Self)]);
            hare.Name = "Clay";
            hare.Flavour = "\"You can be free.\"";
            hare.Description = "On taking any damage, gain 2 probably positive status effects.";
            hare.Icon = ResourceLoader.LoadSprite("item_clay.png");
            hare.EquippedModifiers = [];
            hare.TriggerOn = TriggerCalls.OnDamaged;
            hare.DoesPopUpInfo = true;
            hare.Conditions = [];
            hare.DoesActionOnTriggerAttached = false;
            hare.ConsumeOnTrigger = TriggerCalls.Count;
            hare.ConsumeOnUse = false;
            hare.ConsumeConditions = [];
            hare.ShopPrice = 2;
            hare.IsShopItem = true;
            hare.StartsLocked = true;
            hare.OnUnlockUsesTHE = false;
            hare.UsesSpecialUnlockText = false;
            hare.SpecialUnlockID = UILocID.None;
            hare.item._ItemTypeIDs = [];
            hare.item.AddItem("locked_clay.png", "Aprils_Hare_March_ACH");

            DoubleTargetting frontself = ScriptableObject.CreateInstance<DoubleTargetting>();
            frontself.firstTargetting = Slots.Front;
            frontself.secondTargetting = Slots.Self;

            PerformEffect_Item moon = new PerformEffect_Item("Aprils_PaleSun_TW", [
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyFireSlotEffect>(), 1, frontself)]);
            moon.Name = "Pale Sun";
            moon.Flavour = "\"Look at the center and die.\"";
            moon.Description = "On moving, inflict 1 Fire to the Opposing position and to self.";
            moon.Icon = ResourceLoader.LoadSprite("item_palesun.png");
            moon.EquippedModifiers = [];
            moon.TriggerOn = TriggerCalls.OnMoved;
            moon.DoesPopUpInfo = true;
            moon.Conditions = [];
            moon.DoesActionOnTriggerAttached = false;
            moon.ConsumeOnTrigger = TriggerCalls.Count;
            moon.ConsumeOnUse = false;
            moon.ConsumeConditions = [];
            moon.ShopPrice = 3;
            moon.IsShopItem = false;
            moon.StartsLocked = true;
            moon.OnUnlockUsesTHE = true;
            moon.UsesSpecialUnlockText = false;
            moon.SpecialUnlockID = UILocID.None;
            moon.item._ItemTypeIDs = ["Magic"];
            moon.item.AddItem("locked_palesun.png", "Aprils_Moon_March_ACH");

            PerformEffect_Item clerk = new PerformEffect_Item("Aprils_DoubleBladedKnife_SW", []);
            clerk.Name = "Double-Bladed Knife";
            clerk.Flavour = "\"Who made this??\"";
            clerk.Description = "Deal 50% more damage to enemies to the Right of this party member.\nDeal 50% less damage to enemies to the Left of this party member.";
            clerk.Icon = ResourceLoader.LoadSprite("item_doublebladedknife.png");
            clerk.EquippedModifiers = [];
            clerk.TriggerOn = TriggerCalls.OnWillApplyDamage;
            clerk.DoesPopUpInfo = false;
            clerk.Conditions = [ScriptableObject.CreateInstance<DoubleBladedKnifeCondition>()];
            clerk.DoesActionOnTriggerAttached = false;
            clerk.ConsumeOnTrigger = TriggerCalls.Count;
            clerk.ConsumeOnUse = false;
            clerk.ConsumeConditions = [];
            clerk.ShopPrice = 6;
            clerk.IsShopItem = true;
            clerk.StartsLocked = true;
            clerk.OnUnlockUsesTHE = true;
            clerk.UsesSpecialUnlockText = false;
            clerk.SpecialUnlockID = UILocID.None;
            clerk.item._ItemTypeIDs = ["Knife"];
            clerk.item.AddItem("locked_doublebladedknife.png", "Aprils_Clerk_March_ACH");

            Basic_Item esther = new Basic_Item("Aprils_6AMAlarm_SW");
            esther.Name = "6 AM Alarm";
            esther.Flavour = "\"...Wake up...!\"";
            esther.Description = "After dying, revive this party member after 6 turns at 1 health.";
            esther.Icon = ResourceLoader.LoadSprite("item_6amalarm.png");
            esther.EquippedModifiers = [];
            esther.TriggerOn = TriggerCalls.Count;
            esther.DoesPopUpInfo = false;
            esther.Conditions = [];
            esther.DoesActionOnTriggerAttached = false;
            esther.ConsumeOnTrigger = TriggerCalls.Count;
            esther.ConsumeOnUse = false;
            esther.ConsumeConditions = [];
            esther.ShopPrice = 3;
            esther.IsShopItem = true;
            esther.StartsLocked = true;
            esther.OnUnlockUsesTHE = true;
            esther.UsesSpecialUnlockText = false;
            esther.SpecialUnlockID = UILocID.None;
            esther.item.AddItem("locked_6amalarm.png", "Aprils_Esther_March_ACH");

            PerformEffect_Item rhys = new PerformEffect_Item("Aprils_FriedHumanHand_SW", []);
            rhys.Name = "Fried Human Hand";
            rhys.Flavour = "\"I hope this wasn't from anyone you know...\"";
            rhys.Description = "Heal 60% more to party members with less health than this party member.\nHeal 40% less to party members with more health than this party member.";
            rhys.Icon = ResourceLoader.LoadSprite("item_friedhumanhand.png");
            rhys.EquippedModifiers = [];
            rhys.TriggerOn = TriggerCalls.OnWillApplyHeal;
            rhys.DoesPopUpInfo = false;
            rhys.Conditions = [ScriptableObject.CreateInstance<FriedHumanHandCondition>()];
            rhys.DoesActionOnTriggerAttached = false;
            rhys.ConsumeOnTrigger = TriggerCalls.Count;
            rhys.ConsumeOnUse = false;
            rhys.ConsumeConditions = [];
            rhys.ShopPrice = 6;
            rhys.IsShopItem = true;
            rhys.StartsLocked = true;
            rhys.OnUnlockUsesTHE = true;
            rhys.UsesSpecialUnlockText = false;
            rhys.SpecialUnlockID = UILocID.None;
            rhys.item._ItemTypeIDs = ["Meat"];
            rhys.item.AddItem("locked_friedhumanhand.png", "Aprils_Rhys_March_ACH");

            IncreaseDamageByAmountCondition by2 = ScriptableObject.CreateInstance<IncreaseDamageByAmountCondition>();
            by2.Amount = 2;

            MultiPerformEffectItem wtmiyr = new MultiPerformEffectItem("Aprils_CollateralDamage1999_SW", []);
            wtmiyr.Name = "CollateralDamage1999";
            wtmiyr.Flavour = "\"Merry Christmas Eve!\"";
            wtmiyr.Description = "Increase damage dealt by 2.\nApply 2 Power to damaged targets.";
            wtmiyr.Icon = ResourceLoader.LoadSprite("item_collateraldamage1999.png");
            wtmiyr.EquippedModifiers = [];
            wtmiyr.TriggerOn = AdvancedDamageTrigger.Dealt;
            wtmiyr.DoesPopUpInfo = false;
            wtmiyr.Conditions = [DamageTargetEffectsCondition.Create([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPowerEffect>(), 2, Slots.Self)], true)];
            wtmiyr.DoesActionOnTriggerAttached = false;
            wtmiyr.ConsumeOnTrigger = TriggerCalls.Count;
            wtmiyr.ConsumeOnUse = false;
            wtmiyr.ConsumeConditions = [];
            wtmiyr.ShopPrice = 2;
            wtmiyr.IsShopItem = true;
            wtmiyr.StartsLocked = true;
            wtmiyr.OnUnlockUsesTHE = false;
            wtmiyr.UsesSpecialUnlockText = false;
            wtmiyr.SpecialUnlockID = UILocID.None;
            EffectTrigger wtmiyr_second = new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [by2], false);
            wtmiyr.AddEffectTrigger(wtmiyr_second);
            wtmiyr.item.AddItem("locked_collateraldamage1999.png", "Aprils_Wtmiyr_March_ACH");

            PerformEffect_Item joy = new PerformEffect_Item("Aprils_AluminumCube_TW", []);
            joy.Name = "Aluminum Cube";
            joy.Flavour = "\"Planned Obsoescence\"";
            joy.Description = "Increase healing dealt by 20%.\nRandomize the health colors of healed targets.";
            joy.Icon = ResourceLoader.LoadSprite("item_aluminumcube.png");
            joy.EquippedModifiers = [];
            joy.TriggerOn = TriggerCalls.OnWillApplyHeal;
            joy.DoesPopUpInfo = false;
            joy.Conditions = [ScriptableObject.CreateInstance<AluminumCubeCondition>()];
            joy.DoesActionOnTriggerAttached = false;
            joy.ConsumeOnTrigger = TriggerCalls.Count;
            joy.ConsumeOnUse = false;
            joy.ConsumeConditions = [];
            joy.ShopPrice = 5;
            joy.IsShopItem = false;
            joy.StartsLocked = true;
            joy.OnUnlockUsesTHE = true;
            joy.UsesSpecialUnlockText = false;
            joy.SpecialUnlockID = UILocID.None;
            joy.item.AddItem("locked_aluminumcube.png", "Aprils_Joy_March_ACH");

            PerformEffect_Item patch = new PerformEffect_Item("Aprils_BoneNeedle_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyFrailEffect>(), 2, Slots.Front)]);
            patch.Name = "Bone Needle";
            patch.Flavour = "\"HAHAHAHAHEHEHEAHAHAHAHAHA\"";
            patch.Description = "On being directly damaged, inflict 2 Frail on the Opposing enemy.";
            patch.Icon = ResourceLoader.LoadSprite("item_boneneedle.png");
            patch.EquippedModifiers = [];
            patch.TriggerOn = TriggerCalls.OnDirectDamaged;
            patch.DoesPopUpInfo = true;
            patch.Conditions = [];
            patch.DoesActionOnTriggerAttached = false;
            patch.ConsumeOnTrigger = TriggerCalls.Count;
            patch.ConsumeOnUse = false;
            patch.ConsumeConditions = [];
            patch.ShopPrice = 7;
            patch.IsShopItem = false;
            patch.StartsLocked = true;
            patch.OnUnlockUsesTHE = true;
            patch.UsesSpecialUnlockText = false;
            patch.SpecialUnlockID = UILocID.None;
            patch.item._ItemTypeIDs = ["Knife"];
            patch.item.AddItem("locked_boneneedle.png", "Aprils_Patch_March_ACH");

            PerformEffect_Item six = new PerformEffect_Item("Aprils_PlasticFish_EW", [
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ExtraVariableForNextEffect>(), 0),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomHealBetweenPreviousAndEntryEffect>(), 10, Slots.Self),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ConsumeItemEffect>(), 1, Slots.Self, BasicEffects.DidThat(false))]);
            six.Name = "Plastic Fish";
            six.Flavour = "\"You cought... garbage! 4 cm.\"";
            six.Description = "Heal 0-10 health at the end of each turn.\nIf no healing was dealt, consume this item.";
            six.Icon = ResourceLoader.LoadSprite("item_plasticfish.png");
            six.EquippedModifiers = [];
            six.TriggerOn = TriggerCalls.OnTurnFinished;
            six.DoesPopUpInfo = true;
            six.Conditions = [];
            six.DoesActionOnTriggerAttached = false;
            six.ConsumeOnTrigger = TriggerCalls.Count;
            six.ConsumeOnUse = false;
            six.ConsumeConditions = [];
            six.ShopPrice = 4;
            six.IsShopItem = false;
            six.StartsLocked = true;
            six.OnUnlockUsesTHE = true;
            six.UsesSpecialUnlockText = true;
            six.SpecialUnlockID = UILocID.ItemFishLocationLabel;
            six.item.AddFishItem(3, "locked_plasticfish.png", "Aprils_Six_March_ACH");

            PerformEffect_Item diamond = new PerformEffect_Item("Aprils_BloodDiamond_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<RemoveTargetTimelineAbilityEffect>(), 1, Slots.Front), Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyHasteEffect>(), 1, Slots.Front)]);
            diamond.Name = "Blood Diamond";
            diamond.Flavour = "\"Worth Less Than You Think.\"";
            diamond.Description = "At the end of each turn, cancel 1 of the Opposing enemy's abilities and apply 1 Haste on them.";
            diamond.Icon = ResourceLoader.LoadSprite("item_blooddiamond.png");
            diamond.TriggerOn = TriggerCalls.OnTurnFinished;
            diamond.DoesPopUpInfo = true;
            diamond.Conditions = [];
            diamond.DoesActionOnTriggerAttached = false;
            diamond.ConsumeOnTrigger = TriggerCalls.Count;
            diamond.ConsumeOnUse = false;
            diamond.ConsumeConditions = [];
            diamond.ShopPrice = 8;
            diamond.IsShopItem = false;
            diamond.StartsLocked = true;
            diamond.OnUnlockUsesTHE = true;
            diamond.UsesSpecialUnlockText = false;
            diamond.SpecialUnlockID = UILocID.None;
            diamond.item.AddItem("locked_blooddiamond.png", "Aprils_Rotcore_March_ACH");

            PerformEffect_Item nullref = new PerformEffect_Item("Aprils_NullReferenceException_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<RemoveAllStatusEffectsEffect>(), 1, Slots.Self), Effects.GenerateEffect(MaxHealth.Decrease, 2, Slots.Self, BasicEffects.DidThat(false))]);
            nullref.Name = "NullReferenceException";
            nullref.Flavour = "";
            nullref.Description = "On using an ability, remove all Status Effects from this party member.\nIf no Status Effects were removed, lose 2 maximum health.";
            nullref.Icon = ResourceLoader.LoadSprite("item_nullreferenceexception.png");
            nullref.TriggerOn = TriggerCalls.OnAbilityUsed;
            nullref.DoesPopUpInfo = true;
            nullref.Conditions = [];
            nullref.DoesActionOnTriggerAttached = false;
            nullref.ConsumeOnTrigger = TriggerCalls.Count;
            nullref.ConsumeOnUse = false;
            nullref.ConsumeConditions = [];
            nullref.ShopPrice = 5;
            nullref.IsShopItem = false;
            nullref.StartsLocked = true;
            nullref.OnUnlockUsesTHE = false;
            nullref.UsesSpecialUnlockText = false;
            nullref.SpecialUnlockID = UILocID.None;
            nullref.item._ItemTypeIDs = [];
            nullref.item.AddItem("locked_nullreferenceexception.png", "Aprils_Catten_March_ACH");

            PerformEffect_Item broom = new PerformEffect_Item("Aprils_Broom_SW", [Effects.GenerateEffect(RemoveFieldNoRestrictorEffect.Create("Slip_ID"), 1, Slots.Self), Effects.GenerateEffect(RemoveFieldNoRestrictorEffect.Create("Roots_ID"), 1, Slots.Self), Effects.GenerateEffect(RemoveFieldNoRestrictorEffect.Create("Constricted_ID"), 1, Slots.Self)], true);
            broom.Name = "Broom";
            broom.Flavour = "\"Keep it tidy.\"";
            broom.Description = "On manually moving, remove all Slip, Roots, and Constricted from the position.";
            broom.Icon = ResourceLoader.LoadSprite("item_broom.png");
            broom.TriggerOn = TriggerCalls.OnSwapTo;
            broom.DoesPopUpInfo = true;
            broom.Conditions = [ScriptableObject.CreateInstance<BroomCheckCondition>()];
            broom.DoesActionOnTriggerAttached = false;
            broom.ConsumeOnTrigger = TriggerCalls.Count;
            broom.ConsumeOnUse = false;
            broom.ConsumeConditions = [];
            broom.ShopPrice = 4;
            broom.IsShopItem = true;
            broom.StartsLocked = true;
            broom.OnUnlockUsesTHE = true;
            broom.UsesSpecialUnlockText = false;
            broom.SpecialUnlockID = UILocID.None;
            broom.item._ItemTypeIDs = [];
            broom.item.AddItem("locked_broom.png", "Aprils_Sunflower_March_ACH");

            PerformEffect_Item saea = new PerformEffect_Item("Aprils_Damocles_TW", [
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ExtraVariableForNextEffect>(), 2),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomHealBetweenPreviousAndEntryEffect>(), 5, Targeting.Unit_AllAllies),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPaleEffect>(), 8, Targeting.Unit_AllAllies)]);
            saea.Name = "Damocles";
            saea.Flavour = "\"The String Snaps\"";
            saea.Description = "At the start of each turn, heal all party members 2-5 health and inflict 8 Pale on them.\nThis item is destroyed upon death.";
            saea.Icon = ResourceLoader.LoadSprite("item_damocles.png");
            saea.EquippedModifiers = [];
            saea.TriggerOn = TriggerCalls.OnTurnStart;
            saea.DoesPopUpInfo = true;
            saea.Conditions = [];
            saea.DoesActionOnTriggerAttached = false;
            saea.ConsumeOnTrigger = TriggerCalls.OnDeath;
            saea.ConsumeOnUse = false;
            saea.ConsumeConditions = [];
            saea.ShopPrice = 5;
            saea.IsShopItem = false;
            saea.StartsLocked = true;
            saea.OnUnlockUsesTHE = false;
            saea.UsesSpecialUnlockText = false;
            saea.SpecialUnlockID = UILocID.None;
            saea.item._ItemTypeIDs = ["Magic"];
            saea.item.AddItem("locked_damocles.png", "Aprils_Saea_March_ACH");

            Basic_Item alpha = new Basic_Item("Aprils_YouVoodooDoll_TW");
            alpha.Name = "You Voodoo Doll";
            alpha.Flavour = "\"In the end, it's just you.\"";
            alpha.Description = "Whenever another party member performs an ability, attempt to copy that ability.";
            alpha.Icon = ResourceLoader.LoadSprite("item_youvoodoodoll.png");
            alpha.EquippedModifiers = [];
            alpha.TriggerOn = TriggerCalls.Count;
            alpha.DoesPopUpInfo = false;
            alpha.Conditions = [];
            alpha.DoesActionOnTriggerAttached = false;
            alpha.ConsumeOnTrigger = TriggerCalls.Count;
            alpha.ConsumeOnUse = false;
            alpha.ConsumeConditions = [];
            alpha.ShopPrice = 8;
            alpha.IsShopItem = false;
            alpha.StartsLocked = true;
            alpha.OnUnlockUsesTHE = true;
            alpha.UsesSpecialUnlockText = false;
            alpha.SpecialUnlockID = UILocID.None;
            alpha.item._ItemTypeIDs = ["Magic"];
            alpha.item.AddItem("locked_youvoodoodoll.png", "Aprils_Alpha_March_ACH");

            if (!April.Me) return;

            PerformEffect_Item boneworms = new PerformEffect_Item("Aprils_Boneworms_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<CycleAbilitiesEffect>(), 1, Slots.Self)]);
            boneworms.Name = "Boneworms";
            boneworms.Flavour = "\"Eats away at you\"";
            boneworms.Description = "At the end of each turn, remove this party member's Leftmost ability and give them a random one of their abilities that they didn't have.\nIf they had all of their abilities, give them a random item ability.";
            boneworms.Icon = ResourceLoader.LoadSprite("item_boneworms.png");
            boneworms.EquippedModifiers = [];
            boneworms.TriggerOn = TriggerCalls.OnTurnFinished;
            boneworms.DoesPopUpInfo = true;
            boneworms.Conditions = [];
            boneworms.DoesActionOnTriggerAttached = false;
            boneworms.ConsumeOnTrigger = TriggerCalls.Count;
            boneworms.ConsumeOnUse = false;
            boneworms.ConsumeConditions = [];
            boneworms.ShopPrice = 6;
            boneworms.IsShopItem = true;
            boneworms.StartsLocked = true;
            boneworms.OnUnlockUsesTHE = true;
            boneworms.UsesSpecialUnlockText = false;
            boneworms.SpecialUnlockID = UILocID.None;
            boneworms.item._ItemTypeIDs = ["Meat"];
            boneworms.item.AddItem("locked_boneworms.png", "Aprils_Defacer_March_ACH");

        }
    }
}
